package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class Code_Name_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("[@|#][A-Z][0-9][0-9][0-9]");
  }
}
